services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Weakbit\FallbackCache\Cache\CacheManager:
    public: true
  Weakbit\FallbackCache\EventListener\CacheStatusEventListener:
    tags:
      - name: event.listener
        identifier: 'Weakbit\FallbackCache\EventListener\CacheStatusEventListener'
        event: Weakbit\FallbackCache\EventListener\CacheStatusEvent
