services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Weakbit\FallbackCache\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/**/{Model,Dto,Enum}/*'
      - '../Classes/RateLimiter/Storage/*'
