services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Weakbit\FallbackCache\:
    resource: '../Classes/*'
    exclude: '../Classes/**/{Model,Dto,Enum}/*'

  Weakbit\FallbackCache\EventListener\CacheStatusEventListener:
    tags:
      - name: event.listener
        identifier: 'Weakbit\FallbackCache\EventListener\CacheStatusEventListener'
        event: Weakbit\FallbackCache\Event\CacheStatusEvent

  Weakbit\FallbackCache\EventListener\SystemInformationToolbarCollectorEventListener:
    tags:
      - name: event.listener
        identifier: 'Weakbit\FallbackCache\EventListener\SystemInformationToolbarCollectorEventListener'
        event: TYPO3\CMS\Backend\Backend\Event\SystemInformationToolbarCollectorEvent
